import { create } from 'zustand'
import type { HomeStoreState, Platform, Entry } from '../types'

const DEFAULT_PLATFORMS: Platform[] = [
  { id: 'all', name: '全部', color: '#1C1C1E' },
  { id: 'jd', name: '京东', color: '#E54444' },
  { id: 'taobao', name: '淘宝', color: '#FF6600' },
  // { id: 'pinduoduo', name: '拼多多', color: '#7B3FE4' },
  { id: 'eleme', name: '饿了么', color: '#0EA5E9' },
  // { id: 'douyin', name: '抖音', color: '#161823' },
  { id: 'didi', name: '滴滴', color: '#F76E1E' },
]

/*
const DEFAULT_ENTRIES: Entry[] = [
  {
    id: 'jd_food_001',
    platform: 'jd',
    platformName: '京东',
    platformColor: '#E54444',
    title: '京东爆品双份低至9.9，好事成双 一次两份',
    deeplink:
      'https://union-click.jd.com/jdc?e=1000521676&p=JF8BAPwJK1olXDYDZBoCUBVIMzZNXhpXVhgcFR0DXR9QHDMXQA4KD1heSgINVRYJUz1NQxxBQwNkCgkbSBlJajN9HyRRWUZcFRwaaSNSaxtRcw8LBVlXABdCUQ5LXl8LHCITAXZLVD4fWBtVYAoPeiRhXQNUWFJtCXsUAm8MGl4XXQQLZFtaDEkTADRMXh9NB1ICV1xYDEwnA284UDUUbQcyVFhbAEgQBGwMHFsTWzYCXFlt0fu81NCRz8SGhLangvTzOHsWM2w4G1oUXAIBVFlbD3snAV8LKwV7XAFSAFpdD0x5Xy5dXlxQHlJsVFtYAUITBGs4GVoUXwQyZG5tOHs',
    category: 'food',
    icon: '📦',
    tag: '热门',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'jd_shop_002',
    platform: 'jd',
    platformName: '京东',
    platformColor: '#E54444',
    title: '品质外卖上京东，百亿补贴限时领',
    deeplink:
      'https://union-click.jd.com/jdc?e=1000521676&p=JF8BAeYJK1olXDYDZBoCUBVIMzZNXhpXVhgcDQAZS1RMVnBaRQcLDVBUFwoLWA5PXTB6QgtKAlJfNRoOFhlOUzBXTwYbD19SCwEJVS5fQjsERwNcP15dAgMJehJHXDBcRkxXD1JdAFIfUBRBXjsfSxhDHxpACA4AVTJJXzt0RQ5RAFJ6AVJfD0sXAnhRTQMJD0dALBwfTB9yXStaQjpLBVlHLAtReyoLAG4LH1ocXQ8eVV9cCFxOVTcUSRpXK0VSBzsDTBlOYjFQRB5tCApxNUJeCUgTA2wLGUcUXAcBQwEJXB5qQmNNWB9BSkVWAwoeShVTUTsESRpXSkRcEB0PXCxHXitcF14UXAcDXEkeXBtKZjdUTyZLDwoCQwcFXR9oUygEG0xMBVNWPCM2c0cXFCpQXgZBURJ2UEotDV8fBHt8H08cKBIKU249SStJcBgWWjheI2ZqKz4vCQBLSBx4F1clXDYBVV5ZCU4VA20BK14SWQQGVwUZTQ9PWTsIGFkQWQEyVF5tQyUWM244G10TVQUFUVxfC0IRA18IE1wlhLapg-HE3NSE2t-tzfG7bTYDZF1tCEoWAmsLG1wTWjYyVW5eOBV5AmgKG1wVWA9sCB8ISktKQzxmG14RWAUHVlhtCkoWAW04K2slbTY',

    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'jd_shop_003',
    platform: 'jd',
    platformName: '京东',
    platformColor: '#E54444',
    title: '20元外卖百亿补贴券',
    deeplink:
      'https://union-click.jd.com/jdc?e=1000521676&p=JF8BAPgJK1olXDYDZBoCUBVIMzZNXhpXVhgcFR0DFxcIWDoXSQVJQ1pSCQNDWBlSWyhcBVl9OWFLUV44QUxUfCpXcyZRW0cEXTYqCzFIShAWQwRACU8dDRsBVXtKZm0Oa1lFNGRYBAwUYw9pSjlsaxJDUQoyVW5eCUsTAmoKG1kcbQMFUFxZCxBTRitQQQ8VXgQHUFltCEsnSAEJK1olXQAEXF1aD08eBGcIH2sVVQEyje723_SO1_Cbwuuwi6ysZG5tC3sXAm4JH1gVWgAFZG5fOEgnXQEJHF0UWVFWBjABSR5SVilARDUVWAAFU1pZC3sVAm4KGWslbTYyZA',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'jd_shop_004',
    platform: 'jd',
    platformName: '京东',
    platformColor: '#E54444',
    title: '京东外卖满25减13 限时抢',
    deeplink:
      'https://union-click.jd.com/jdc?e=1000521676&p=JF8BAPgJK1olXDYDZBoCUBVIMzZNXhpXVhgcFR0DFxcIWDoXSQVJQ1pSCQNDWBlSWyhcBV5nJn8EUR8dVE5VXDtUUhtHXmNxMCUcYx8feA8WQwRACU8dDRsBVXsWVhJbQSZvFmR0IgwvbQtsQhxXWTxlUQoyVW5eCUsTAmoKG1kcbQMFUFxZCxBTRitQQQ8VXgQHUFltCEsnSAEJK1olXQAEXF1bCEgRBW8OEmsVVQEyje723_SO1_Cbwuuwi6ysZG5tC3sXAm4JH1gVWgAFZG5fOEgnXQEJHF0WCAVWATABSR5RBDhDWzUVWQYHXVlVD3sVAm4KGWslbTYyZA',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'jd_shop_005',
    platform: 'jd',
    platformName: '京东',
    platformColor: '#E54444',
    title: '京东团购频道大牌特价',
    deeplink:
      'https://union-click.jd.com/jdc?e=1000521676&p=JF8BAQkJK1olXDYDZBoCUBVIMzZNXhpXVhgcFR0DFxcIWDoXSQVJQ0BCSg4PTRNQV3ELTAwVX2BaHwpbaw91QS9UZDsRB115Bj9ZQS9tHTdXTg9cQl9HCANTWxtEVzJ6QgtKAlJfWBsYTU8VMzEWbhxUVGJCNjdedSNlWRB_BRhgJEAOWG5cOEgWA2sJHlkVXw8yUVlZCk8UWCtNXwNPCQYBVltZD3sXA19DdVolXDYCUlhVC00XBmoBElkUbQYKU26EuODAvPbchMjM7aPU_vBtOHsUM28JGloRXgYFUlltOEknAF9WdVoSDVMKUl1dZhdWVilYHgxLMwYGVVhYCk8RM20JGlkXbTYyZG5t',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'jd_shop_006',
    platform: 'jd',
    platformName: '京东',
    platformColor: '#E54444',
    title: '京东9块9包邮特惠，入口直达',
    deeplink:
      'https://pxtndj5l.jutuike.cn/#/pages/elite/index?code=pXTndj5l&eliteId=10&showMenu=false',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'mt_shop_001',
    platform: 'meituan',
    platformName: '美团',
    platformColor: '#F5A623',
    title: '美团外卖红包天天领',
    deeplink: 'http://dpurl.cn/O5p05o7z',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'mt_shop_002',
    platform: 'meituan',
    platformName: '美团',
    platformColor: '#F5A623',
    title: '爆品低价大牌饮品 福利超多多！',
    deeplink: 'http://dpurl.cn/wXgL8coz',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'mt_shop_003',
    platform: 'meituan',
    platformName: '美团',
    platformColor: '#F5A623',
    title: '美团霸王餐',
    deeplink:
      'https://offsiteact.meituan.com/act/cps/promotion?p=1109842471627096064',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'mt_shop_004',
    platform: 'meituan',
    platformName: '美团',
    platformColor: '#F5A623',
    title: '满43减13元大额神券,天天领',
    deeplink: 'http://dpurl.cn/qcEAY9Oz',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'mt_shop_005',
    platform: 'meituan',
    platformName: '美团',
    platformColor: '#F5A623',
    title: '美团外卖品质商家红包',
    deeplink: 'http://dpurl.cn/I4ejd37z',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'mt_shop_006',
    platform: 'meituan',
    platformName: '美团',
    platformColor: '#F5A623',
    title: '下单试吃得返现，最低1元吃外卖',
    deeplink: 'https://wxaurl.cn/7RlpqGHfQ8h',
    category: 'shop',
    icon: '🎟️',
    appScheme: 'openapp.jdmobile://',
  },
  {
    id: 'taobao_shop_001',
    platform: 'taobao',
    platformName: '淘宝',
    platformColor: '#FF6600',
    title: '闪购超级品牌日，领取大额红包',
    deeplink:
      'https://AdPuCDRF.jutuike.cn/#/pages/taobao/shangou?&act_id=60&sid=h5mall&code=AdPuCDRF',
    category: 'shop',
    icon: '🏪',
    tag: '热门',
    appScheme: 'taobao://',
  },
  {
    id: 'taobao_shop_002',
    platform: 'taobao',
    platformName: '淘宝',
    platformColor: '#FF6600',
    title: '【口令】超值爆品，加倍补贴！大红包',
    deeplink:
      'https://AdPuCDRF.jutuike.cn/#/pages/taobao/shangou?&act_id=124&sid=h5mall&code=AdPuCDRF',
    category: 'shop',
    icon: '🏷️',
    appScheme: 'taobao://',
  },
  {
    id: 'taobao_shop_003',
    platform: 'taobao',
    platformName: '淘宝',
    platformColor: '#FF6600',
    title: '淘宝闪购，领15元大额红包',
    deeplink:
      'https://AdPuCDRF.jutuike.cn/#/pages/taobao/shangou?&act_id=127&sid=h5mall&code=AdPuCDRF',
    category: 'shop',
    icon: '🏷️',
    appScheme: 'taobao://',
  },
  {
    id: 'taobao_shop_003',
    platform: 'taobao',
    platformName: '淘宝',
    platformColor: '#FF6600',
    title: '📢 淘宝大放水啦，15减14元',
    deeplink:
      'https://AdPuCDRF.jutuike.cn/#/pages/taobao/shangou?&act_id=125&sid=h5mall&code=AdPuCDRF',
    category: 'shop',
    icon: '🏷️',
    appScheme: 'taobao://',
  },
  {
    id: 'eleme_food_001',
    platform: 'eleme',
    platformName: '饿了么',
    platformColor: '#0EA5E9',
    title: '饿了么霸王餐',
    deeplink:
      'https://h5cms.jutuike.cn/#/pages/taobao/shangou?&act_id=112&sid=h5mall&code=AdPuCDRF',
    category: 'food',
    icon: '🎁',
    tag: '新上线',
    appScheme: 'eleme://',
  },
  {
    id: 'eleme_food_002',
    platform: 'eleme',
    platformName: '饿了么',
    platformColor: '#0EA5E9',
    title: '饿了么，红包天天领',
    deeplink:
      'https://h5.ele.me/adminiappsub/pages/h5/index?configKey=BDLM_ELE_H5_DG_TC&scene=8f8e4684a34e48ff854ba4dfaca613ad',
    category: 'food',
    icon: '🎁',
    tag: '新上线',
    appScheme: 'eleme://',
  },
  {
    id: 'eleme_food_003',
    platform: 'eleme',
    platformName: '饿了么',
    platformColor: '#0EA5E9',
    title: '每天可领，每周五，五折红包',
    deeplink:
      'https://h5.ele.me/adminiappsub/pages/h5/index?configKey=BDLM_ELE_H5_DG_TC&scene=49def33996c14ef09cdbd50011cead4e',
    category: 'food',
    icon: '🎁',
    tag: '新上线',
    appScheme: 'eleme://',
  },
  {
    id: 'eleme_food_004',
    platform: 'eleme',
    platformName: '饿了么',
    platformColor: '#0EA5E9',
    title: '饿了么21城消费日活动，8元红包天天领',
    deeplink:
      'https://h5cms.jutuike.cn/#/pages/toMiniProgram/detail?&act_id=133&sid=h5mall&code=AdPuCDRF&activity_id=10817&act_id2=94',
    category: 'food',
    icon: '🎁',
    tag: '新上线',
    appScheme: 'eleme://',
  },
  {
    id: 'didi_trip_001',
    platform: 'didi',
    platformName: '滴滴等网约车平台',
    platformColor: '#F76E1E',
    title: '网约车&顺风，最高可领100元优惠券',
    deeplink:
      'https://vv.didi.cn/rlqb33L?source_id=465352jutuikeh5mall&ref_from=dunion',
    category: 'trip',
    icon: '🚕',
    tag: '热门',
    appScheme: 'didiglobal://',
  },
  {
    id: 'didi_trip_002',
    platform: 'didi',
    platformName: '滴滴',
    platformColor: '#F76E1E',
    title: '滴滴打车红包天天领',
    deeplink:
      'https://vv.didi.cn/86zJERv?source_id=465352jutuikeh5mall&ref_from=dunion',
    category: 'trip',
    icon: '🚕',
    tag: '热门',
    appScheme: 'didiglobal://',
  },
  {
    id: 'didi_trip_003',
    platform: 'didi',
    platformName: '滴滴',
    platformColor: '#F76E1E',
    title: '滴滴代驾，最高可领20元立减券',
    deeplink:
      'https://v.didi.cn/qgJmkGz?source_id=465352jutuikeh5mall&ref_from=dunion',
    category: 'trip',
    icon: '🚲',
    appScheme: 'didiglobal://',
  },
]
*/

export const useHomeStore = create<HomeStoreState>(set => ({
  selectedPlatform: 'all',
  searchKeyword: '',
  platforms: DEFAULT_PLATFORMS,
  entries: [],
  setSelectedPlatform: platform => set({ selectedPlatform: platform }),
  setSearchKeyword: keyword => set({ searchKeyword: keyword }),
  setHomeConfig: ({ platforms, entries }) =>
    set({
      platforms: platforms?.length ? platforms : DEFAULT_PLATFORMS,
      entries: entries || [],
    }),
}))
